# .github/workflows/deploy-blog.yml
name: Deploy Blog to GitHub Pages

on:
  workflow_run:
    workflows: ["Translate new blog posts"]   # ← exact name above
    types: [completed]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages-blog
  cancel-in-progress: true   # avoids duplicate builds on rapid pushes :contentReference[oaicite:1]{index=1}

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # skip on failure
    runs-on: ubuntu-latest

    steps:
      # ① Get the latest commit on default branch (already includes translations)
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }   # full history for SSGs that use git data :contentReference[oaicite:2]{index=2}

      # ② Install and build the blog
      - run: |
          npm ci
      - run: |
          npm run build

      # ③ Publish `blog/dist` to separate Pages branch
      - uses: peaceiris/actions-gh-pages@v3 :contentReference[oaicite:3]{index=3}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: blog.plexicus.ai
          publish_branch: gh-pages-blog
