name: Translate new blog posts

on:
  push:
    paths:
      - 'blog/src/content/blog/**/*.md'
      - 'blog/src/content/blog/**/*.mdx'
    paths-ignore:
      - 'blog/src/content/blog/translations/**'

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:           # needed to push the translated files back
      contents: write
      pull-requests: write

    env:
      AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_DEPLOYMENT: gpt-4o-realtime   # change if you provisioned a different name
      MODEL_FALLBACK: gpt-35-turbo-1106
      LANG_CODES: "en,de,fr,ja,ko,it,nl,sv,no,da,fi,pt,zh,ar,he,tr,pl,cs,id"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # so we can diff against the previous commit

      - name: Calculate changed markdown files
        id: changed
        run: |
          echo "matrix=$(git diff --name-only HEAD^ | \
          grep -E 'blog/src/content/blog/.*\.(md|mdx)$' | \
          grep -v 'blog/src/content/blog/translations/' | \
          jq -Rsc 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

      - name: Exit early if nothing to translate
        if: ${{ steps.changed.outputs.matrix == '[]' }}
        run: echo "No new blog posts to translate."

      - name: Set up Python
        if: ${{ steps.changed.outputs.matrix != '[]' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ steps.changed.outputs.matrix != '[]' }}
        run: pip install openai==1.* pydantic==2.* python-frontmatter==1.*

      - name: Run translator
        if: ${{ steps.changed.outputs.matrix != '[]' }}
        run: |
          python scripts/translate_blog.py '${{ steps.changed.outputs.matrix }}'

      - name: Commit & push translations
        if: ${{ steps.changed.outputs.matrix != '[]' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(translations): add multilingual copies"
          file_pattern: blog/src/content/blog/translations
